
# Load environemnt variables from .env file
spring.config.import=file:./.env[.properties]

# Port used by the backend
server.port=8080

# Create and drop the database schema on startup and shutdown
spring.jpa.hibernate.ddl-auto=create-drop

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5332/${POSTGRES_DB}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Custom annotations used
spring.application.encryptionKey=${JWT_SECRET}
stripe.apiKey=${STRIPE_API_KEY}
